name: Todo App Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Cloning project
      uses: actions/checkout@v2
    - name: List files
      run: |
        ls ${{ github.workspace }}
    - name: Setup Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install project
      run: npm install
    - name: Test project
      run: npm test
